# Generated by Django 4.1.7 on 2023-03-06 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('summ', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('summ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salary')),
                ('sanction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sanction')),
            ],
        ),
        migrations.CreateModel(
            name='Bonuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('summ', models.IntegerField()),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salary')),
            ],
        ),
    ]
