# Generated by Django 4.1.7 on 2023-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_salary_summ_alter_salary_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='summ',
            field=models.IntegerField(default=20000),
        ),
    ]
