# Generated by Django 4.1.7 on 2023-03-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
